/// SET UP VARIABLES

// MAXIMUM HEIGHT OF THE CUBOID
max_depth = 100;

// OBJECT TO "FOLLOW"
obj_to_follow = obj_camera;

// A FACTOR TO "SLOW DOWN" THE EFFECT, CHANGE THIS TO MAKE THE EFFECT
// MORE DRASTIC

factor = 16;

// INITIALISE OTHER VARIABLES
hdepth = 0;
vdepth = 0;
