var name = argument[0];
var x_origin = argument[1];
var y_origin = argument[2];
var recoil = argument[3];
var price = argument[4];
var img_index = argument[5];
var floor_image_index = argument[6];
var damage = argument[7];
var bullet_type = argument[8];
var primary_clip = argument[9];
var secondary_clip = argument[10];
var flame_origin_x = argument[11];
var flame_origin_y = argument[12];
var shoot_time = argument[13];
var reload_time = argument[14];
var bullet_speed = argument[15];
var clip_size = argument[16];

var gun = ds_map_create();
ds_map_add(gun, "name", name);
ds_map_add(gun, "x_origin", x_origin);
ds_map_add(gun, "y_origin", y_origin);
ds_map_add(gun, "recoil", recoil);
ds_map_add(gun, "price", price);
ds_map_add(gun, "image_index", img_index);
ds_map_add(gun, "floor_image_index", floor_image_index);
ds_map_add(gun, "damage", damage);
ds_map_add(gun, "bullet_type", bullet_type);
ds_map_add(gun, "primary_clip", primary_clip);
ds_map_add(gun, "secondary_clip", secondary_clip);
ds_map_add(gun, "flame_origin_x", flame_origin_x);
ds_map_add(gun, "flame_origin_y", flame_origin_y);
ds_map_add(gun, "shoot_time", shoot_time);
ds_map_add(gun, "reload_time", reload_time);
ds_map_add(gun, "bullet_speed", bullet_speed);
ds_map_add(gun, "clip_size", clip_size);
ds_list_add(global.guns, gun);